### ISSUE TITLE
MCMC not converging when running dms2_batch_prefs

### ISSUE THREAD

**Issue by jiroop** [jbloomlab/dms_tools2#10]
The readme file in the attached directory describes the error in more detail, but this is the error I get when running dms2_batch_prefs:

2018-11-02 13:35:54,248 - INFO - Getting results for site 206...
2018-11-02 13:35:54,248 - ERROR - Terminating dms2_prefs with ERROR
Traceback (most recent call last):
  File "/home/jroop/.local/bin/dms2_prefs", line 304, in main
    .format(r, logstring))
RuntimeError: Failed for site 206:
	Beginning MCMC at Fri Nov  2 11:59:53 2018
	After 4 MCMC chains each of 20000 steps, mean R = 1.2541643122083816 and mean Neff = 37.9
	MCMC failed to converge. Doing retry 1 with 40000 iterations per chain.
	After 4 MCMC chains each of 40000 steps, mean R = 1.539564031833223 and mean Neff = 23.35
	MCMC failed to converge. Doing retry 2 with 80000 iterations per chain.
	After 4 MCMC chains each of 80000 steps, mean R = 1.2654302097288201 and mean Neff = 33.2
	MCMC failed to converge. Doing retry 3 with 160000 iterations per chain.
	After 4 MCMC chains each of 160000 steps, mean R = 1.530588807580061 and mean Neff = 57.35
	MCMC failed to converge. Doing retry 4 with 320000 iterations per chain.
	After 4 MCMC chains each of 320000 steps, mean R = 1.2578045547551282 and mean Neff = 151.3
	MCMC failed to converge. Doing retry 5 with 640000 iterations per chain.
	After 4 MCMC chains each of 640000 steps, mean R = 1.5417707240750493 and mean Neff = 199.05
	MCMC FAILED to converge after all attempts at Fri Nov  2 13:35:52 2018.

[181101_MCMC_debug_short.tar.gz](https://github.com/jbloomlab/dms_tools2/files/2544378/181101_MCMC_debug_short.tar.gz)

**Comment by jbloom** [comment]
@jiroop: It's not a bug per se, but just the MCMC isn't converging. It is getting close to converging (I think we require an Neff of 300 and we get to 200), but it is very inefficient. I could make an option to increase the number of MCMC steps which will improve convergence if you want.

But I think the main problem appears to come from the data, not the algorithm.

At site 206, here are the codon counts for the  *DNA-mut2* sample, which is your mutant library:

  
  206,CCA,4,12,7,9,21,21,2,4,5,8,4,2,2,11,21,8,25,19,4,20,700638,61,49,33,16,3,13,12,32,10,3,12,2,2,2,3,21,10,6,3,5,0,16,0,0,9,3,8,13,2,4,7,30,13,6,6,7,11,5,2,1,7,3,8

And here are the counts for the *WT-DNA* sample, which is supposed to be the control to estimate the error rate for this sample:

    206,CCA,0,0,0,0,458,0,0,0,0,0,0,0,0,0,0,0,39,0,0,0,587586,2,39,21,14,0,0,0,46,0,0,0,0,0,0,0,299,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,295,28,0,1,0,0,0,0,0,0,0,0

You can see that there are several positions where this error control has counts much higher than the actual mutant library for which it is supposed to be estimating error rates (these are the sites with 458, 299, and 295 counts). This violates the assumptions of the analysis, which is that the errors that we are trying to correct for should be rarer than the observed rate in the mutant library sample (which is the sum of real mutations plus errors). Is there oxidative damage or some other obviously spurious signal going on at site 206 in your *WT-DNA* error control?

One possible solution would be to use your wildtype virus (*WT-inf*) as the control for both. It seems to have more reasonable error counts at site 206: 

    206,CCA,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,332121,0,4,1,0,0,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,0,1,0,0,0,0,0,0,0,0,0

But it would be good to look at the plots for these samples to get a good sense of what is going on before deciding.

**Comment by jiroop** [comment]
@jbloom I’ve worked out what the problem is with site 206. 

The sequencing files that I am using to infer preferences from are a combination of my initial and resequenced libraries. Both were prepped independently from the same viral DNA extraction. The problem which led to the excess of counts for mutant codons in the WT-DNA library was a stupid mistake that I made when combining the initial and resequenced reads, which resulted in all of the reads from the initial sequencing run being duplicated in the combined reads file. So the high counts for several mutant codons the WT-DNA codoncounts file are probably the result of sequencing errors that should have been present as singleton reads and discarded, but instead were present twice and were not thrown out. 

I fixed this duplication issue and remapped all sequencing reads, then tried again to infer preferences. 

The MCMC now fails to converge at different sites, with each of the rhesus replicates failing at a different site. The counts at these sites don’t seem to offer any clear explanation for what is wrong, at least to my eyes. Here are the counts from relevant files for site 553 which failed in replicate 1:

DNAmut1_codoncounts.csv:553,AGC,2,53,2,2,1,2,6,11,6,509121,0,136,0,14,1,1,5,5,7,2,3,5,8,0,5,11,5,3,3,11,0,2,1,1,5,0,0,10,3,3,0,22,0,4,3,3,5,1,1,1,0,0,1,5,2,3,0,8,5,3,6,7,4,1

RHMmut1_codoncounts.csv:553,AGC,0,204,0,0,9,1,5,42,12,569950,0,193,0,60,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,53,249,0,0,6,6,0,0,22,0,0,0,28,0,0,0,0,0,0,0,7,0,0,0,4,0,0,0,13,0,0

WTDNA_codoncounts.csv:553,AGC,0,0,0,0,0,0,0,0,0,2154,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

WTinf_codoncounts.csv:553,AGC,0,4,0,0,0,0,0,0,1,24065,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Interestingly the error message for this site indicates that Neff reached > 900 but still failed to converge:

2018-11-15 09:59:37,516 - INFO - Getting results for site 553...
2018-11-15 09:59:37,516 - ERROR - Terminating dms2_prefs with ERROR
Traceback (most recent call last):
File "/home/jroop/.local/bin/dms2_prefs", line 304, in main
    .format(r, logstring))
RuntimeError: Failed for site 553:
Beginning MCMC at Thu Nov 15 07:26:42 2018
After 4 MCMC chains each of 20000 steps, mean R = 1.3474237857034943 and mean Neff = 55.0
MCMC failed to converge. Doing retry 1 with 40000 iterations per chain.
After 4 MCMC chains each of 40000 steps, mean R = 1.3399402423684363 and mean Neff = 71.25
MCMC failed to converge. Doing retry 2 with 80000 iterations per chain.
After 4 MCMC chains each of 80000 steps, mean R = 1.341139122439191 and mean Neff = 154.55
MCMC failed to converge. Doing retry 3 with 160000 iterations per chain.
After 4 MCMC chains each of 160000 steps, mean R = 1.1038373651379232 and mean Neff = 220.55
MCMC failed to converge. Doing retry 4 with 320000 iterations per chain.
After 4 MCMC chains each of 320000 steps, mean R = 1.3539073589145239 and mean Neff = 469.3
MCMC failed to converge. Doing retry 5 with 640000 iterations per chain.
After 4 MCMC chains each of 640000 steps, mean R = 1.2668130762240688 and mean Neff = 910.15
MCMC FAILED to converge after all attempts at Thu Nov 15 09:59:35 2018.


I also tried inferring preferences with the resequenced reads only, rather than a combination of initial and resequenced. Preferences are inferred for both Rhm replicates here, but one of the Hu selected replicates fails.

Perhaps relevant as well is that preferences can be inferred for all samples when only sequencing reads from the initial sequencing run are used. 

What are you thoughts on this? I can link another zip file that replicates these new errors if useful.

**Comment by jbloom** [comment]
@jiroop: Can you point me to the overall Jupyter notebook that is running this analysis? 

The reason it is failing to converge is that I think I have the current MCMC thresholds set at requiring either R < 1.1 and Neff > 100, or R > 1.15 and Neff > 300. Your MCMC isn't getting there.

It isn't a bug in the MCMC per se, but just things aren't converging. Presumably that means that there is something with the structure of the data that is making it "hard" to converge. It's not obvious to me what that it is, but these usually converge on most datasets so either it is really bad luck or something unusual. Maybe by looking at the overall Jupyter notebook and other aspects of the data it will be possible to figure this out?

**Comment by jiroop** [comment]
@jbloom Here's the notebook I've been using. I agree it seems unusual. thought perhaps it had something to do with trying to infer preferences after a hard selection (i.e. rhesus receptors), but the fact that it seems to happen with the Hu selected dataset argues against that. 

/fh/fast/bloom_j/computational_notebooks/jroop/2016_env_DMS/171212_deep_mutational_scan/181030_final_DMS_analysis/analysis_notebook.ipynb

**Comment by jbloom** [comment]
@jiroop: I can't figure out why there is this convergence problem, although the thing that jumps out is that the *WTDNA* sample has **very low** depth. At the site in question, you have just 2,154 counts for *WTDNA*, but > 500,000 for the mutant samples.

Given how low these *WTDNA* counts are, it is unlikely to be a reliable error control. The average mutation is at a frequency of about 0.0002 / 63 = 3e-6 in you *WTDNA*, but since your counts are only about 2000, for any given mutation you will only estimate frequencies of 0 or > 1 / 2000 = 0.005. I would speculate that this low coverage might be causing the MCMC convergence problems as I don't know if we've ever tried samples with such low and disparate coverage across samples.

My suggestions is to just use the *WTinf* sample as the error control for both pre- and post-selection. This isn't ideal since it has a slightly higher error rate than *WTDNA* and so is a bit inflated for the pre-selection error control. Also, the *WTinf* sample is also very low coverage, although still an order of magnitude better than *WTDNA*. However, even given that fact it is probably more accurate than using a *WTDNA* control with such low depth given the points in the prior paragraph.

The other option is to use one of @adingens's  wildtype plasmid or virus samples as a control. These would have better coverage, although it's also not ideal as they aren't from matched experiments.
