### ISSUE TITLE
AttributeError: module 'jupyter' has no attribute '__version__' when running dms2_batch_bcsubamp

### ISSUE THREAD

**Issue by yqsoh** [jbloomlab/dms_tools2#4]
From summary.log file:

``
2017-10-12 16:05:37,495 - INFO - Progress is being logged to ./results/codoncounts/su
mmary.log
2017-10-12 16:05:39,163 - ERROR - Error
Traceback (most recent call last):
  File "/home/yqsoh/.local/lib/python3.6/site-packages/dms_tools2/utils.py", line 87,
 in initLogger
    logger.info("{0}\n".format(sessionInfo()))
  File "/home/yqsoh/.local/lib/python3.6/site-packages/dms_tools2/utils.py", line 38,
 in sessionInfo
    v = importlib.import_module(modname).__version__
AttributeError: module 'jupyter' has no attribute '__version__'
``

**Comment by jbloom** [comment]
@yqsoh: This should be fixed in version 2.1.0, which is now available for installation using `pip`. Let me know if the problem persists even with that newer version.
